### PR TITLE
fix files behavior on node, and generally remove redundancy in the files key

### LINKED ISSUE #199: Missing wasm-bindgen file in package.json
Hey team! I'm hitting an issue with the packing step of `wasm-pack`. I think I'm missing a file in my `package.json`'s files section. It's affecting module resolution after I `npm install` the output from `wasm-pack pack`.

Consider the test fixture `js-hello-world`. After `wasm-pack init -t nodejs`, `wasm-bindgen` generates a typescript file, two javascript files, and one WASM file:

```bash 
$ ls -al pkg 
total 624
drwxr-xr-x  9 mciantyre  staff     288 Jul  6 17:08 .
drwxr-xr-x  9 mciantyre  staff     288 Jul  6 17:33 ..
-rw-r--r--  1 mciantyre  staff      51 Jul  6 17:57 README.md
-rw-r--r--  1 mciantyre  staff   74708 Jul  6 17:08 js-hello-world-0.1.0.tgz
-rw-r--r--  1 mciantyre  staff      65 Jul  6 17:58 js_hello_world.d.ts
-rw-r--r--  1 mciantyre  staff    4294 Jul  6 17:58 js_hello_world.js
-rw-r--r--  1 mciantyre  staff     423 Jul  6 17:58 js_hello_world_bg.js
-rw-r--r--  1 mciantyre  staff  216481 Jul  6 17:58 js_hello_world_bg.wasm
-rw-r--r--  1 mciantyre  staff     437 Jul  6 17:57 package.json
```

But the `package.json` is missing `js_hello_world_bg.js`:

```json
  "files": [
    "js_hello_world_bg.wasm",
    "js_hello_world.d.ts"
  ],
```

It seems that if that third file isn't provided, `wasm-pack pack` doesn't include it in the output tar. Then, after I `npm install` the tar and require the package, node throws a module resolution error.

As a minimum example, from the `tests/fixtures/js-hello-world` example:

```bash
$ wasm-pack init -t nodejs
$ mkdir example && cd example
$ npm init -y
$ npm install ../pkg/js-hello-world-0.1.0.tgz
$ cat << EOF > index.js
  var lib = require('js-hello-world');
  EOF
$ node index.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './js_hello_world_bg'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/mciantyre/Projects/wasm-pack/tests/fixtures/js-hello-world/example/node_modules/js-hello-world/js_hello_world.js:178:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

```

If I go back to `pkg/package.json` to make it look like

```javascript
  "files": [
    "js_hello_world_bg.wasm",
    "js_hello_world.d.ts",
    "js_hello_world_bg.js" // new file here
  ],
```

re-pack with `wasm-pack pack`, and re-install the tar with `npm install`, everything is good.

Sorry if this is already a known issue. If it's more helpful to have another example, let me know and I can put something together.

I have what I believe to be a fix for `wasm-pack`. My patch worked on this example and my other use-case. Say the word, and I'll open a PR!

Versions of all the things:

- wasm-pack 0.4.0
- node v10.6.0
- npm 6.1.0
- rustc 1.28.0-nightly (e3bf634e0 2018-06-28)
- MacOS 10.13.5

### PR DESCRIPTION
**Pull request by ashleygwilliams**
fixes #199 (FOR REAL THIS TIME)

this PR does several things:
- passes the value of the target flag to the `write_package_json` method
- optionally includes a `_bg.js` file in the `files` key if the `target` is `nodejs`
- updates `files` key to NOT include the file in `main` (it is unecessary)
- adds a test to ensure correct behavior on node
- cleans up tests to test for correct `files` key

### CODE REVIEW

File: src/manifest.rs [hunk 1]
```diff
@@ -90,6 +97,13 @@ impl CargoManifest {
             None => {}
         }
 
+        match js_bg_file {
+            Some(ref js_bg_file) => {
+                files.push(js_bg_file.to_string());
+            }
+            None => {}
+        }
```
Comment (fitzgen) [inline src/manifest.rs]: Nitpick: I think this would be nicer as

```rust
if let Some(ref f) = js_bg_file {
    files.push(f.to_string());
}
```
