### PR TITLE
Corrected files included in package.json for bundler / no target (#837)

### LINKED ISSUE #837: wasm-pack build --target bundler not including *_bg.js file in package.json
## 🐛 Bug description
When running `wasm-pack build --target bundler --scope scopename modulename`, there is are both *.js and *_bg.js files generated. the package.json file looks like this
`
{
  "name": "@scopename/modulename",
  "collaborators": [
    "arlo <arlo@purcell.live>"
  ],
  "version": "0.4.3",
  "files": [
    "modulename_bg.wasm",
    "modulename.js",
    "modulename.d.ts"
  ],
  "module": "modulename.js",
  "types": "modulename.d.ts",
  "sideEffects": false
}
`

#### 🤔 Expected Behavior
I think the `modulename.js` line in `files` should be `modulename_bg.js`, since `modulename.js` file will be included anyway because of the `"module": "modulename.js"` line. I'm not sure about that detail, but when i do `wasm-pack pack`, the generated tar ball is missing the `modulename_bg.js` file, so my module doesn't work

#### 👟 Steps to reproduce
`wasm-pack build --target bundler --scope scopename modulename`

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.9.1
rustc version: rustc 1.43.0 (4fb7144ed 2020-04-20)

### PR DESCRIPTION
**Pull request by lucashorward**
Make sure these boxes are checked! 📦✅

- [x] You have the latest version of `rustfmt` installed
```bash
$ rustup component add rustfmt
```
- [x] You ran `cargo fmt` on the code base before submitting
- [x] You reference which issue is being closed in the PR text

✨✨ 😄 Thanks so much for contributing to wasm-pack! 😄 ✨✨

Closes #837

`wasm-pack build` and `wasm-pack build --target bundler` generate a _bg.js file, but it is not added to the package.json. The file that is added, *.js will however reference the _bg.js, so when the package is distributed (both through `pack` or `publish`) it is not usable.

This change will fix that by passing the correct bool value to npm_data

As is the same for my other PR, there is some test failure that I locally also have on the master branch. Please let me know how to address this if possible

### CODE REVIEW

File: src/manifest/mod.rs [hunk 1]
```diff
@@ -734,7 +734,7 @@ impl CrateData {
         disable_dts: bool,
         out_dir: &Path,
     ) -> NpmPackage {
-        let data = self.npm_data(scope, false, disable_dts, out_dir);
+        let data = self.npm_data(scope, true, disable_dts, out_dir);
```
Comment (Pauan) [inline src/manifest/mod.rs:737]: This should be `false`. The `to_commonjs` method should also use `false`, only `to_esmodules` should be `true`.

Comment (lucashorward) [reply src/manifest/mod.rs:737]: But then there would be no change in behavior, and the issue as described would not be fixed? Please let me know if there is a better way of fixing this issue!

Comment (Pauan) [reply src/manifest/mod.rs:748]: This is the situation in the old code:

* `to_commonjs` -> `true`
* `to_esmodules` -> `false`
* `to_web` -> `false`
* `to_nomodules` -> `false`

This is the situation in your code:

* `to_commonjs` -> `true`
* `to_esmodules` -> `true`
* `to_web` -> `false`
* `to_nomodules` -> `true`

However it is supposed to be like this:

* `to_commonjs` -> `false`
* `to_esmodules` -> `true`
* `to_web` -> `false`
* `to_nomodules` -> `false`

It is only the `bundler` target (`to_esmodules`) which has the extra `_bg.js` file, the rest don't.

Comment (lucashorward) [reply src/manifest/mod.rs]: Thank you for the explanation - I have made the changes. However, I noticed in this and my previous pr that the test `build_with_and_without_wasm_bindgen_debug` keeps failing locally, and now I see that the same has happened on master. Originally I also had this issue on master locally so I thought it was a configuration issue on my side, but as it also fails in the CI I doubt that that is the case. Do you have any idea why this test fails?

Comment (Pauan) [reply src/manifest/mod.rs]: Yeah, I need to look into why that's failing, you can ignore that.

**Comment by Pauan** [comment]
Thanks!

**Comment by Kurble** [comment]
Is a release scheduled anytime soon in order to fix this issue?

**Comment by Corey600** [comment]
> Is a release scheduled anytime soon in order to fix this issue?

+1

**Comment by lucashorward** [comment]
@ashleygwilliams

**Comment by igrep** [comment]
Same here. This bug prevents us from running even a simple example (e.g. https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm). So this patch should be released soon.

**Comment by lucashorward** [comment]
A workaround would be to reference this git repository directly in the cargo.toml:
`wasm-pack = { git = "https://github.com/rustwasm/wasm-pack" }`
But do note that that may include other unreleased changes that have been merged to `master` as well.

**Comment by igrep** [comment]
Let me add an easier workaround: adding the `_bg.js` file to the generated package.json manually.
